name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: Docker Build
      run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}

    - name: Docker Login
      run: docker login  -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ github.sha }}
