name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: Check docker 
      run: docker version
      
      
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
